
name: AutoRun

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 0/7 * * ?

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: pip
        run: pip3 install -r requirements.txt
      
