name: AutoRun

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0/6 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: pip
        run: pip3 install -r requirements.txt

      - name: run
        run: python3 Notify-Action.py ${{ secrets.SENDKEY }} ${{ secrets.COOKIES }}
